### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by curly60e** [dennisreimann/kindle-display#11]
Hello I tested this code on my Kindle, it works fine but, I noted that it doesn't update the image automatically so I created a python file that refresh it every 50 seconds ish.

![imagen](https://user-images.githubusercontent.com/55191248/102377382-58fb1080-3fa3-11eb-991e-2d955f144662.png)

I don't know much of bash hehe, thats why I did it with python.

```
import os
import time as t

while True:

    os.system("./cron.sh")
    t.sleep(50)

```
Hope it helps.

**Comment by dennisreimann** [comment]
Hey, thanks – this is what the [cronjob on the Kindle](https://github.com/dennisreimann/kindle-display/blob/master/kindle/etc/crontab/root#L8) is supposed to do :)

**Comment by curly60e** [comment]
Haha! Yeah, but in the server it doesn't do it at least in mine lol

**Comment by dennisreimann** [comment]
Ah ok, you should set up a similar cronjob on the server as well. The docs mention it in the last paragraph and I now added an example for that, see 146597ce6a84c095936bc6432fa4cf7585501e03.

Thanks for the pointer!

**Comment by curly60e** [comment]
Cool! Thanks!
