### ISSUE TITLE
Quote/Rate missing (sometimes)

### ISSUE THREAD

**Issue by frennkie** [dennisreimann/kindle-display#12]
I just set this up (still nede to charge and then Jailreak my Kindle) and noticed that sometimes not all data is displayed on the screen.

I looked at the [code ](https://github.com/dennisreimann/kindle-display/blob/master/server/views/index.pug#L11) and saw that the quote is omitted if it is 220 characters or longer. I think this makes sense due to the size constraints of the screen. Leaving this here in case anybody else wonders.

But I also had a case where the secondary rate information was missing. 5 minutes later it was back. I'm not quite sure what [Line12](https://github.com/dennisreimann/kindle-display/blob/master/server/views/index.pug#L12) is supposed to do (any why).

**Comment by dennisreimann** [comment]
Regarding the rate: sometimes fetching the info doesn't work – network issues, the rate provider being down or timing out might be the issue.

**Comment by frennkie** [comment]
Makes sense.. :-)
